create table CLIENTINFO
(
  IP             VARCHAR2(20),
  TOKEN          VARCHAR2(50),
  WEIXINID       VARCHAR2(30),
  WEIXINNAME     VARCHAR2(100),
  CREATETIME     DATE,
  ENDTIME        DATE,
  CLIENTSTATUS   VARCHAR2(10),
  COMPANYNAME    VARCHAR2(100),
  AREADESC       VARCHAR2(100),
  CLIENTADMIN    VARCHAR2(20),
  CLIENTPASSWORD VARCHAR2(50),
  CONTACTNUMBER  VARCHAR2(20),
  REMARK         VARCHAR2(200)
);